jira:
  secret: ATATT3xFfGF0W5dqyN2L2I_WE-19ZtIcbLu8pzcpeBw0xPU_wO75tsppZu8Cow-IKLla_fSjiy6KFFlbPFOk54fGsJjTi9zBvIC-7DXtCBotoXIIoOrQ2nYyzm4JY7KmCrkRPDaxm8_QZv-4E4C7DnZk0KjaAICSGhmYVaZB5IMhnJpKWix5pk4=13AFA3D4 
  user-name: dasujjwal1996@gmail.com
  base-url: https://dasujjwal1996.atlassian.net
  ticket-url: /rest/api/2/issue
